### ISSUE TITLE
Doesn't work in Firefox 47.0

### ISSUE THREAD

**Issue by vanoven** [bakulf/priv8#28]
doesn't work anymore in firefox 47

TypeError: docShell.setIsApp is not a function
priv8.configureWindow@chrome://priv8/content/modules/priv8.jsm:268:5

I managed to replace `setIsApp` with

`let attr = docShell.getOriginAttributes();
attr.appId = aId;
docShell.setOriginAttributes(attr);`

I can't find a way to set the frameType but it seems to already work again.
I'm new to javascript and addon but I hope it helps.

**Comment by bakulf** [comment]
\o/ Thanks! I'll apply your help!

**Comment by bakulf** [comment]
I landed the fix and I pushed a new version. It will be available soon!
