### ISSUE TITLE
Doesn't work in latest FF 48.0a2.

### ISSUE THREAD

**Issue by aindlq** [bakulf/priv8#27]
Doesn't work in FF dev channel. Possible reason - http://stackoverflow.com/a/36567596/124722

Trace:
```
console.error: priv8: 
  Message: TypeError: aWindow.QueryInterface is not a function
  Stack:
    priv8.configureWindow@chrome://priv8/content/modules/priv8.jsm:262:20
priv8.openSandbox@chrome://priv8/content/modules/priv8.jsm:139:5
priv8.openSandboxByName@chrome://priv8/content/modules/priv8.jsm:103:9
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://id-at-baku-dot-priv8/lib/main.js:232:3
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
portEmit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/sandbox.js:356:7
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
onContentEvent/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/sandbox.js:397:5
delay/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/lang/functional/concurrent.js:38:20
notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9

```

**Comment by bakulf** [comment]
This is fixed.

**Comment by aindlq** [comment]
Still getting the same error with latest priv8 and Firefox 52.0a2 (2016-12-02) (64-bit).

**Comment by bakulf** [comment]
Can you send me the error log? It would be easier for me to fix this issue. Thanks!

**Comment by bakulf** [comment]
Ok! I know what the issue is: priv8 doesn't support e10s yet!
You are using FF52. Disable e10s and priv8 will work. Or wait until I fix the e10s support.
Thanks!

**Comment by bakulf** [comment]
Ok! I know what the issue is: priv8 doesn't support e10s yet!
You are using FF52. Disable e10s and priv8 will work. Or wait until I fix the e10s support.
Thanks!

**Comment by bakulf** [comment]
sorry for the double comment.
I'm working on the porting of priv8 to e10s. It should be ready soon.

**Comment by aindlq** [comment]
Thank you for the hint. Works fine in non e10s window.
