### ISSUE TITLE
FF ESR 45.7.0 throws "docShell.getOriginAttributes is not a function"

### ISSUE THREAD

**Issue by Beurt** [bakulf/priv8#40]
Hi,

I'm eager to use Priv8, but unfortunately it doesn't seem to work with my FF 45.7.0 (Mageia Linux 5).

On a fresh user profile, no extensions or modules installed and default settings the errors thrown are:

`[xguest@localhost ~]$ firefox
Priv8.jsm - init
Priv8.jsm - getSandboxNames
Priv8.jsm - highlightBrowser
Priv8.jsm - First time, let's store the default style.
Priv8.jsm - non-e10s mode
console.error: priv8: 
  Message: TypeError: docShell.getOriginAttributes is not a function
  Stack:
    priv8.getOriginAttributes@chrome://priv8/content/modules/priv8.jsm:360:9
priv8.highlightBrowser@chrome://priv8/content/modules/priv8.jsm:420:5
highlightBrowser@resource://id-at-baku-dot-priv8/lib/main.js:92:3
refreshWindows@resource://id-at-baku-dot-priv8/lib/main.js:45:1
@resource://id-at-baku-dot-priv8/lib/main.js:322:1
run@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:746:1

*************************
A coding exception was thrown in a Promise resolution callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: TypeError: docShell.getOriginAttributes is not a function
Full stack: priv8.getOriginAttributes@chrome://priv8/content/modules/priv8.jsm:360:9
priv8.highlightBrowser@chrome://priv8/content/modules/priv8.jsm:420:5
highlightBrowser@resource://id-at-baku-dot-priv8/lib/main.js:92:3
refreshWindows@resource://id-at-baku-dot-priv8/lib/main.js:45:1
@resource://id-at-baku-dot-priv8/lib/main.js:322:1
run@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:746:1

*************************
console.error: priv8: 
  Message: TypeError: docShell.getOriginAttributes is not a function
  Stack:
    priv8.getOriginAttributes@chrome://priv8/content/modules/priv8.jsm:360:9
priv8.highlightBrowser@chrome://priv8/content/modules/priv8.jsm:420:5
highlightBrowser@resource://id-at-baku-dot-priv8/lib/main.js:92:3
refreshWindows@resource://id-at-baku-dot-priv8/lib/main.js:45:1
@resource://id-at-baku-dot-priv8/lib/main.js:322:1
run@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:746:1

Priv8.jsm - highlightBrowser
Priv8.jsm - non-e10s mode
console.error: priv8: 
  Message: TypeError: docShell.getOriginAttributes is not a function
  Stack:
    priv8.getOriginAttributes@chrome://priv8/content/modules/priv8.jsm:360:9
priv8.highlightBrowser@chrome://priv8/content/modules/priv8.jsm:420:5
highlightBrowser@resource://gre/modules/commonjs/toolkit/loader.js -> resource://id-at-baku-dot-priv8/lib/main.js:92:3
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://id-at-baku-dot-priv8/lib/main.js:78:1
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
tabEmit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:261:31
tabEventListener@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:316:23
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
initialize/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/observer.js:50:11
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
initialize/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/observer.js:82:9
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
handleEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/windows/observer.js:49:5

Priv8.jsm - getSandboxNames
Priv8.jsm - non-e10s mode
console.error: priv8: 
  Message: TypeError: docShell.getOriginAttributes is not a function
  Stack:
    priv8.getOriginAttributes@chrome://priv8/content/modules/priv8.jsm:360:9
refreshButtonIcons@resource://gre/modules/commonjs/toolkit/loader.js -> resource://id-at-baku-dot-priv8/lib/main.js:54:5
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://id-at-baku-dot-priv8/lib/main.js:74:3
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
tabEmit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:261:31
tabEventListener@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:316:23
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
handleEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/observer.js:109:5
addTab@chrome://browser/content/tabbrowser.xml:1882:13
loadOneTab@chrome://browser/content/tabbrowser.xml:1402:23
openLinkIn@chrome://browser/content/utilityOverlay.js:355:1
openUILinkIn@chrome://browser/content/utilityOverlay.js:193:3
BrowserOpenTab@chrome://browser/content/browser.js:1960:3
BrowserOpenNewTabOrWindow@chrome://browser/content/browser.js:7937:5
oncommand@chrome://browser/content/browser.xul:1:1

Priv8.jsm - highlightBrowser
Priv8.jsm - non-e10s mode
console.error: priv8: 
  Message: TypeError: docShell.getOriginAttributes is not a function
  Stack:
    priv8.getOriginAttributes@chrome://priv8/content/modules/priv8.jsm:360:9
priv8.highlightBrowser@chrome://priv8/content/modules/priv8.jsm:420:5
highlightBrowser@resource://gre/modules/commonjs/toolkit/loader.js -> resource://id-at-baku-dot-priv8/lib/main.js:92:3
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://id-at-baku-dot-priv8/lib/main.js:78:1
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
tabEmit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:261:31
tabEventListener@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:316:23
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
initialize/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/observer.js:50:11
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
handleEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/observer.js:109:5
updateCurrentBrowser@chrome://browser/content/tabbrowser.xml:1145:15
onselect@chrome://browser/content/browser.xul:1:44
set_selectedIndex@chrome://global/content/bindings/tabbox.xml:664:13
set_selectedPanel@chrome://global/content/bindings/tabbox.xml:683:13
set_selectedIndex@chrome://global/content/bindings/tabbox.xml:399:15
set_selectedItem@chrome://global/content/bindings/tabbox.xml:431:34
set_selectedTab@chrome://global/content/bindings/tabbox.xml:110:15
set_selectedTab@chrome://browser/content/tabbrowser.xml:2798:11
loadOneTab@chrome://browser/content/tabbrowser.xml:1417:15
openLinkIn@chrome://browser/content/utilityOverlay.js:355:1
openUILinkIn@chrome://browser/content/utilityOverlay.js:193:3
BrowserOpenTab@chrome://browser/content/browser.js:1960:3
BrowserOpenNewTabOrWindow@chrome://browser/content/browser.js:7937:5
oncommand@chrome://browser/content/browser.xul:1:1

`

I hope there can be a fix for this Firefox ESR version.

**Comment by bakulf** [comment]
Right. ESR is not supported yet.

**Comment by Beurt** [comment]
It is very unfortunate. Nevertheless thank you very much for this outstanding tool !
